### ISSUE TITLE
Module 2: Kiểm thử module 2.

### ISSUE THREAD

**Issue by manhhdv** [manhdvuetk63/Square-and-Circle#21]
Kiểm tra xem module 2 còn thiếu sót nào để bổ sung, hoàn thiện.

**Comment by haongo00** [comment]
Animation, hiệu ứng chuyển màn hình chưa hoàn chỉnh

**Comment by manhhdv** [comment]
Nói rõ ra đi bạn để còn sửa nào .

**Comment by haongo00** [comment]
animation quả bóng chuyển màn hơi nhanh, chưa đk đẹp
và quả bóng còn lag
Khi trả lời câu hỏi cuối cùng xong thì việc chuyển sang màn hình chiến thắng không có thời gian delay, cái này nên cho thêm thời gian delay thì có vẻ ổn đó.
